// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type OptionsLegacyParser } from '@hey-api/client-fetch'
import type {
  GetApiTodoListsData,
  GetApiTodoListsError,
  GetApiTodoListsResponse,
} from './types.gen'

export const client = createClient(createConfig())

/**
 * Get paginated todo lists
 */
export const getApiTodoLists = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<GetApiTodoListsData, ThrowOnError>
) => {
  return client.get<GetApiTodoListsResponse, GetApiTodoListsError, ThrowOnError>({
    ...options,
    url: '/api/todo-lists',
  })
}
