// This file is auto-generated by @hey-api/openapi-ts

export type GetApiTodoListsData = {
  query: {
    /**
     * Page number
     */
    page: number
    /**
     * Number of items per page
     */
    perPage: number
  }
}

export type GetApiTodoListsResponse = {
  items: Array<{
    id?: number
    title?: string
    ownerUserId?: number
    createdAt?: string
    updatedAt?: string | null
  }>
  total: number
  page: number
  perPage: number
  lastPage: number
}

export type GetApiTodoListsError = unknown
